language: julia
sudo: false
os:
  - linux
#  - osx

julia:
 - 1.3
 - nightly

allow_failures:
 - julia: nightly

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      name: "HTML"
      after_success: skip

after_success:
  - julia -e 'using Pkg; import LightGraphs; cd(joinpath(dirname(pathof(LightGraphs)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
#    - julia -e 'using Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.23.4"); Pkg.add(ps); Pkg.pin(ps)'
#    - julia -e 'using Pkg; import LightGraphs; joinpath(dirname(pathof(LightGraphs)); include(joinpath("docs", "make.jl"))'
#    - export JULIA_NUM_THREADS=4; julia -e 'Pkg.add("PkgBenchmark"); using PkgBenchmark; benchmarkpkg("LightGraphs", promptoverwrite=false)'
