name: CI-nightly
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  test:
    name: Julia nightly - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: nightly
          arch: x64
      - uses: julia-actions/julia-buildpkg@latest
      # remove this after 2.0
      - name: test package
        run: julia --color=yes --project -e 'using Pkg; Pkg.test(coverage=true, julia_args=["--depwarn=no"])'
      # uncomment after 2.0
      # - uses: julia-actions/julia-runtest@latest
